server:
  port: 9090
spring:
  datasource:
    #    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.140.141.90:3306/finance_revenue?characterEncoding=utf-8
    username: finance_revenue
    password: 6zhjED5yLYWk8Hn6
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml  #mybatis指定数据库xml文件
  typeAliasesPackage: com.example.boranqichacha.Entity      #指定实体类
  configuration:
    map-underscore-to-camel-case: false  #关闭驼峰，实体类的 *_*映射
    auto-mapping-behavior: full
    use-generated-keys: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 0
      logic-not-delete-value: 1
